// Generated by ChatGPT

// Blokus (6x6) Forge viz for: Board.position : pfunc Coord -> Placement
// Colors every Coord that appears in Board.position.

function blokusViz6x6() {
  const N = 6;

  // ---------- styling ----------
  const css = `
    .blokus-wrap { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }
    .blokus-grid {
      display: grid;
      grid-template-columns: repeat(${N}, 28px);
      grid-template-rows: repeat(${N}, 28px);
      gap: 2px;
      padding: 8px;
      background: #111827;
      border-radius: 12px;
      width: max-content;
    }
    .blokus-cell {
      width: 28px; height: 28px;
      background: #F3F4F6;
      border-radius: 6px;
      border: 1px solid rgba(0,0,0,.08);
      position: relative;
      box-sizing: border-box;
    }
    .blokus-cell.filled { border: 1px solid rgba(0,0,0,.25); }
    .blokus-coord {
      position: absolute;
      right: 2px; bottom: 1px;
      font-size: 9px;
      color: rgba(0,0,0,.45);
      user-select: none;
    }
    .blokus-title { font-weight: 650; margin: 6px 0 8px; color: #111827; }
    .blokus-sub { font-size: 12px; color: #6B7280; margin-bottom: 8px; }
    .blokus-legend { margin-top: 10px; display: flex; flex-wrap: wrap; gap: 8px; }
    .blokus-pill {
      display: inline-flex; align-items: center; gap: 6px;
      padding: 6px 8px;
      background: #F9FAFB;
      border: 1px solid rgba(0,0,0,.08);
      border-radius: 999px;
      font-size: 12px;
    }
    .blokus-swatch { width: 12px; height: 12px; border-radius: 3px; border: 1px solid rgba(0,0,0,.2); }
    .blokus-warn { margin-top: 8px; font-size: 12px; color: #991B1B; }
  `;
  function ensureStyle() {
    if (document.getElementById("blokus-style")) return;
    const s = document.createElement("style");
    s.id = "blokus-style";
    s.textContent = css;
    document.head.appendChild(s);
  }

  // ---------- helpers for Forge instance ----------
  function getSingletonAtom(sig) {
    // for `one sig` (like your Board)
    const ts = sig.tuples();
    if (!ts || ts.length === 0) return null;
    return ts[0]._atoms[0];
  }

  function getIntField(atom, fieldRel) {
    // atom.join(fieldRel) -> set of Int atoms (should be 1)
    const s = atom.join(fieldRel);
    const t = s.tuples();
    if (!t || t.length === 0) return null;
    const raw = t[0]._atoms[0].toString();
    const n = parseInt(raw, 10);
    return Number.isFinite(n) ? n : null;
  }

  // ---------- palette ----------
  const palette = [
    "#EF4444", "#F97316", "#F59E0B", "#84CC16", "#22C55E",
    "#06B6D4", "#3B82F6", "#6366F1", "#A855F7", "#EC4899",
    "#14B8A6", "#94A3B8"
  ];
  const placementColor = new Map();
  function colorForPlacement(pAtom) {
    const key = pAtom.toString();
    if (!placementColor.has(key)) {
      placementColor.set(key, palette[placementColor.size % palette.length]);
    }
    return placementColor.get(key);
  }

  // ---------- render ----------
  ensureStyle();
  div.innerHTML = "";
  div.className = "blokus-wrap";
  div.style.overflow = "auto";

  const title = document.createElement("div");
  title.className = "blokus-title";
  title.textContent = "Blokus board (6×6)";
  div.appendChild(title);

  const sub = document.createElement("div");
  sub.className = "blokus-sub";
  sub.textContent = "Colored squares are occupied cells from Board.position.";
  div.appendChild(sub);

  const grid = document.createElement("div");
  grid.className = "blokus-grid";
  div.appendChild(grid);

  // cells[x][y]
  const cellEl = Array.from({ length: N }, () => Array.from({ length: N }, () => null));
  for (let y = N - 1; y >= 0; y--) {
    for (let x0 = 0; x0 < N; x0++) {
      const c = document.createElement("div");
      c.className = "blokus-cell";
      const lab = document.createElement("div");
      lab.className = "blokus-coord";
      lab.textContent = `${x0},${y}`;
      c.appendChild(lab);
      grid.appendChild(c);
      cellEl[x0][y] = c;
    }
  }

  // ---------- fill from Board.position ----------
  const boardAtom = getSingletonAtom(Board);
  if (!boardAtom) {
    const warn = document.createElement("div");
    warn.className = "blokus-warn";
    warn.textContent = "No Board atom found (is Board declared as `one sig Board`?).";
    div.appendChild(warn);
    return;
  }

  let tuples;
  try {
    tuples = boardAtom.join(position).tuples(); // (Coord, Placement)
  } catch (e) {
    console.error(e);
    const warn = document.createElement("div");
    warn.className = "blokus-warn";
    warn.textContent = "Could not read Board.position (is it named `position`?).";
    div.appendChild(warn);
    return;
  }

  console.log("Board.position tuples:", tuples.length);

  for (let i = 0; i < tuples.length; i++) {
    const coordAtom = tuples[i]._atoms[0];
    const placementAtom = tuples[i]._atoms[1];

    const xVal = getIntField(coordAtom, x);
    const yVal = getIntField(coordAtom, y);

    // Uncomment to debug a few
    // if (i < 10) console.log("coord", coordAtom.toString(), "->", xVal, yVal, "placement", placementAtom.toString());

    if (xVal === null || yVal === null) continue;
    if (xVal < 0 || xVal >= N || yVal < 0 || yVal >= N) continue;

    const el = cellEl[xVal][yVal];
    if (!el) continue;

    const col = colorForPlacement(placementAtom);
    el.classList.add("filled");
    el.style.background = col;

    // tooltip with anchor + shape if accessible
    let tip = `cell (${xVal},${yVal})\nplacement: ${placementAtom}`;
    try {
      const anch = placementAtom.join(anchor).tuples()?.[0]?._atoms?.[0];
      if (anch) {
        const ax = getIntField(anch, x);
        const ay = getIntField(anch, y);
        if (ax !== null && ay !== null) tip += `\nanchor: (${ax},${ay})`;
      }
    } catch (_) {}
    try {
      const sAtom = placementAtom.join(s).tuples()?.[0]?._atoms?.[0];
      if (sAtom) tip += `\nshape: ${sAtom}`;
    } catch (_) {}
    el.title = tip;
  }

  // ---------- legend ----------
  const legend = document.createElement("div");
  legend.className = "blokus-legend";
  div.appendChild(legend);

  if (placementColor.size === 0) {
    const pill = document.createElement("div");
    pill.className = "blokus-pill";
    pill.textContent = "No colored cells: Board.position is empty OR coords not in 0..8.";
    legend.appendChild(pill);
  } else {
    for (const [p, col] of placementColor.entries()) {
      const pill = document.createElement("div");
      pill.className = "blokus-pill";
      const sw = document.createElement("span");
      sw.className = "blokus-swatch";
      sw.style.background = col;
      const txt = document.createElement("span");
      txt.textContent = p;
      pill.appendChild(sw);
      pill.appendChild(txt);
      legend.appendChild(pill);
    }
  }
}

blokusViz6x6();